
//=======================================================
//  This code is generated by Terasic System Builder
//=======================================================

`include "structures.vh"

module DE2_115(

	//////////// CLOCK //////////
	input 		          		CLOCK_50,
	input 		          		CLOCK2_50,
	input 		          		CLOCK3_50,

	//////////// Sma //////////
	input 		          		SMA_CLKIN,
	output		          		SMA_CLKOUT,

	//////////// LED //////////
	output		     [8:0]		LEDG,
	output		    [17:0]		LEDR,

	//////////// KEY //////////
	input 		     [3:0]		KEY,

	//////////// EX_IO //////////
	inout 		     [6:0]		EX_IO,

	//////////// SW //////////
	input 		    [17:0]		SW,

	//////////// SEG7 //////////
	output		     [6:0]		HEX0,
	output		     [6:0]		HEX1,
	output		     [6:0]		HEX2,
	output		     [6:0]		HEX3,
	output		     [6:0]		HEX4,
	output		     [6:0]		HEX5,
	output		     [6:0]		HEX6,
	output		     [6:0]		HEX7,

	//////////// LCD //////////
	output		          		LCD_BLON,
	inout 		     [7:0]		LCD_DATA,
	output		          		LCD_EN,
	output		          		LCD_ON,
	output		          		LCD_RS,
	output		          		LCD_RW,

	//////////// RS232 //////////
	input 		          		UART_CTS,
	output		          		UART_RTS,
	input 		          		UART_RXD,
	output		          		UART_TXD,

	//////////// PS2 for Keyboard and Mouse //////////
	inout 		          		PS2_CLK,
	inout 		          		PS2_CLK2,
	inout 		          		PS2_DAT,
	inout 		          		PS2_DAT2,

	//////////// SDCARD //////////
	output		          		SD_CLK,
	inout 		          		SD_CMD,
	inout 		     [3:0]		SD_DAT,
	input 		          		SD_WP_N,

	//////////// VGA //////////
	output		     [7:0]		VGA_B,
	output		          		VGA_BLANK_N,
	output		          		VGA_CLK,
	output		     [7:0]		VGA_G,
	output		          		VGA_HS,
	output		     [7:0]		VGA_R,
	output		          		VGA_SYNC_N,
	output		          		VGA_VS,

	//////////// Audio //////////
	input 		          		AUD_ADCDAT,
	inout 		          		AUD_ADCLRCK,
	inout 		          		AUD_BCLK,
	output		          		AUD_DACDAT,
	inout 		          		AUD_DACLRCK,
	output		          		AUD_XCK,

	//////////// I2C for EEPROM //////////
	output		          		EEP_I2C_SCLK,
	inout 		          		EEP_I2C_SDAT,

	//////////// I2C for Audio Tv-Decoder  //////////
	output		          		I2C_SCLK,
	inout 		          		I2C_SDAT,

	//////////// Ethernet 0 //////////
	output		          		ENET0_GTX_CLK,
	input 		          		ENET0_INT_N,
	input 		          		ENET0_LINK100,
	output		          		ENET0_MDC,
	inout 		          		ENET0_MDIO,
	output		          		ENET0_RST_N,
	input 		          		ENET0_RX_CLK,
	input 		          		ENET0_RX_COL,
	input 		          		ENET0_RX_CRS,
	input 		     [3:0]		ENET0_RX_DATA,
	input 		          		ENET0_RX_DV,
	input 		          		ENET0_RX_ER,
	input 		          		ENET0_TX_CLK,
	output		     [3:0]		ENET0_TX_DATA,
	output		          		ENET0_TX_EN,
	output		          		ENET0_TX_ER,
	input 		          		ENETCLK_25,

	//////////// Ethernet 1 //////////
	output		          		ENET1_GTX_CLK,
	input 		          		ENET1_INT_N,
	input 		          		ENET1_LINK100,
	output		          		ENET1_MDC,
	inout 		          		ENET1_MDIO,
	output		          		ENET1_RST_N,
	input 		          		ENET1_RX_CLK,
	input 		          		ENET1_RX_COL,
	input 		          		ENET1_RX_CRS,
	input 		     [3:0]		ENET1_RX_DATA,
	input 		          		ENET1_RX_DV,
	input 		          		ENET1_RX_ER,
	input 		          		ENET1_TX_CLK,
	output		     [3:0]		ENET1_TX_DATA,
	output		          		ENET1_TX_EN,
	output		          		ENET1_TX_ER,

	//////////// TV Decoder //////////
	input 		          		TD_CLK27,
	input 		     [7:0]		TD_DATA,
	input 		          		TD_HS,
	output		          		TD_RESET_N,
	input 		          		TD_VS,

	//////////// USB 2.0 OTG (Cypress CY7C67200) //////////
	output		     [1:0]		OTG_ADDR,
	output		          		OTG_CS_N,
	inout 		    [15:0]		OTG_DATA,
	input 		          		OTG_INT,
	output		          		OTG_RD_N,
	output		          		OTG_RST_N,
	output		          		OTG_WE_N,

	//////////// IR Receiver //////////
	input 		          		IRDA_RXD,

	//////////// SDRAM //////////
	output		    [12:0]		DRAM_ADDR,
	output		     [1:0]		DRAM_BA,
	output		          		DRAM_CAS_N,
	output		          		DRAM_CKE,
	output		          		DRAM_CLK,
	output		          		DRAM_CS_N,
	inout 		    [31:0]		DRAM_DQ,
	output		     [3:0]		DRAM_DQM,
	output		          		DRAM_RAS_N,
	output		          		DRAM_WE_N,

	//////////// SRAM //////////
	output		    [19:0]		SRAM_ADDR,
	output		          		SRAM_CE_N,
	inout 		    [15:0]		SRAM_DQ,
	output		          		SRAM_LB_N,
	output		          		SRAM_OE_N,
	output		          		SRAM_UB_N,
	output		          		SRAM_WE_N,

	//////////// Flash //////////
	output		    [22:0]		FL_ADDR,
	output		          		FL_CE_N,
	inout 		     [7:0]		FL_DQ,
	output		          		FL_OE_N,
	output		          		FL_RST_N,
	input 		          		FL_RY,
	output		          		FL_WE_N,
	output		          		FL_WP_N
);



//=======================================================
//  REG/WIRE declarations
//=======================================================

// Active-high reset derived from board reset button
wire sys_reset = ~KEY[0];

// Per-channel bundles so the two eth_tse instances can be built with a generate loop.
// Note: DE2_115_ENET*_RX_DATA/TX_DATA are only 4 bits wide, so the PHY is wired to the
// core's MII bus (m_*), not the 8-bit GMII bus (gm_*), which is tied off/unused here.
wire [3:0] enet_rx_data [0:1];
wire       enet_rx_dv   [0:1];
wire       enet_rx_err  [0:1];
wire       enet_rx_crs  [0:1];
wire       enet_rx_col  [0:1];
wire       enet_rx_clk  [0:1];
wire       enet_tx_clk  [0:1];
wire       enet_link100 [0:1];

// Per-channel Avalon-MM control port bundles (internal only, no external Avalon master present)
logic [7:0]  tse_ctrl_addr      [0:1];
logic [31:0] tse_ctrl_readdata  [0:1];
logic        tse_ctrl_read      [0:1];
logic [31:0] tse_ctrl_writedata [0:1];
logic        tse_ctrl_write     [0:1];
logic        tse_ctrl_waitreq   [0:1];

avalon_st_t tse_tx [0:1];
avalon_st_t tse_rx [0:1];
logic       tse_tx_ready [0:1];
logic       tse_rx_ready [0:1];

// No external Avalon master is present for the control port; keep both channels idle.
assign tse_ctrl_addr[0]      = 8'd0;
assign tse_ctrl_read[0]      = 1'b0;
assign tse_ctrl_writedata[0] = 32'd0;
assign tse_ctrl_write[0]     = 1'b0;

assign tse_ctrl_addr[1]      = 8'd0;
assign tse_ctrl_read[1]      = 1'b0;
assign tse_ctrl_writedata[1] = 32'd0;
assign tse_ctrl_write[1]     = 1'b0;

// tse_tx/tse_rx and their ready handshakes are driven by the eth_core instances below.

wire [3:0] enet_tx_data [0:1];
wire       enet_tx_en   [0:1];
wire       enet_tx_er   [0:1];

assign enet_rx_data[0] = ENET0_RX_DATA;
assign enet_rx_dv[0]   = ENET0_RX_DV;
assign enet_rx_err[0]  = ENET0_RX_ER;
assign enet_rx_crs[0]  = ENET0_RX_CRS;
assign enet_rx_col[0]  = ENET0_RX_COL;
assign enet_rx_clk[0]  = ENET0_RX_CLK;
assign enet_tx_clk[0]  = ENET0_TX_CLK;
assign enet_link100[0] = ENET0_LINK100;

assign enet_rx_data[1] = ENET1_RX_DATA;
assign enet_rx_dv[1]   = ENET1_RX_DV;
assign enet_rx_err[1]  = ENET1_RX_ER;
assign enet_rx_crs[1]  = ENET1_RX_CRS;
assign enet_rx_col[1]  = ENET1_RX_COL;
assign enet_rx_clk[1]  = ENET1_RX_CLK;
assign enet_tx_clk[1]  = ENET1_TX_CLK;
assign enet_link100[1] = ENET1_LINK100;

assign ENET0_TX_DATA = enet_tx_data[0];
assign ENET0_TX_EN   = enet_tx_en[0];
assign ENET0_TX_ER   = enet_tx_er[0];

assign ENET1_TX_DATA = enet_tx_data[1];
assign ENET1_TX_EN   = enet_tx_en[1];
assign ENET1_TX_ER   = enet_tx_er[1];

// GTX_CLK/MDIO/MDC/RST_N are not driven by this MAC instance (MII 10/100 only, no MDIO
// controller present in eth_tse); tie them off sensibly.
assign ENET0_GTX_CLK = 1'b0;
assign ENET0_MDC     = 1'b0;
assign ENET0_MDIO    = 1'bz;
assign ENET0_RST_N   = KEY[0];

assign ENET1_GTX_CLK = 1'b0;
assign ENET1_MDC     = 1'b0;
assign ENET1_MDIO    = 1'bz;
assign ENET1_RST_N   = KEY[0];

//=======================================================
//  Structural coding
//=======================================================

genvar eth_ch;
generate
	for (eth_ch = 0; eth_ch < 2; eth_ch = eth_ch + 1) begin : eth_tse_gen
		eth_tse eth_tse_inst (
			.clk           (CLOCK_50),
			.reset         (sys_reset),
			.reg_addr      (tse_ctrl_addr[eth_ch]),
			.reg_data_out  (tse_ctrl_readdata[eth_ch]),
			.reg_rd        (tse_ctrl_read[eth_ch]),
			.reg_data_in   (tse_ctrl_writedata[eth_ch]),
			.reg_wr        (tse_ctrl_write[eth_ch]),
			.reg_busy      (tse_ctrl_waitreq[eth_ch]),
			.tx_clk        (enet_tx_clk[eth_ch]),
			.rx_clk        (enet_rx_clk[eth_ch]),
			.set_10        (~enet_link100[eth_ch]),
			.set_1000      (1'b0),
			.eth_mode      (),
			.ena_10        (),
			.gm_rx_d       (8'd0),
			.gm_rx_dv      (1'b0),
			.gm_rx_err     (1'b0),
			.gm_tx_d       (),
			.gm_tx_en      (),
			.gm_tx_err     (),
			.m_rx_d        (enet_rx_data[eth_ch]),
			.m_rx_en       (enet_rx_dv[eth_ch]),
			.m_rx_err      (enet_rx_err[eth_ch]),
			.m_tx_d        (enet_tx_data[eth_ch]),
			.m_tx_en       (enet_tx_en[eth_ch]),
			.m_tx_err      (enet_tx_er[eth_ch]),
			.m_rx_crs      (enet_rx_crs[eth_ch]),
			.m_rx_col      (enet_rx_col[eth_ch]),
			.ff_rx_clk     (enet_rx_clk[eth_ch]),
			.ff_tx_clk     (enet_tx_clk[eth_ch]),
			.ff_rx_data    (tse_rx[eth_ch].data),
			.ff_rx_eop     (tse_rx[eth_ch].eop),
			.rx_err        (tse_rx[eth_ch].error),
			.ff_rx_mod     (tse_rx[eth_ch].empty),
			.ff_rx_rdy     (tse_rx_ready[eth_ch]),
			.ff_rx_sop     (tse_rx[eth_ch].sop),
			.ff_rx_dval    (tse_rx[eth_ch].valid),
			.ff_tx_data    (tse_tx[eth_ch].data),
			.ff_tx_eop     (tse_tx[eth_ch].eop),
			.ff_tx_err     (tse_tx[eth_ch].error[0]),
			.ff_tx_mod     (tse_tx[eth_ch].empty),
			.ff_tx_rdy     (tse_tx_ready[eth_ch]),
			.ff_tx_sop     (tse_tx[eth_ch].sop),
			.ff_tx_wren    (tse_tx[eth_ch].valid),
			.magic_wakeup  (),
			.magic_sleep_n (1'b1),
			.ff_tx_crc_fwd (1'b0),
			.ff_tx_septy   (),
			.tx_ff_uflow   (),
			.ff_tx_a_full  (),
			.ff_tx_a_empty (),
			.rx_err_stat   (),
			.rx_frm_type   (),
			.ff_rx_dsav    (),
			.ff_rx_a_full  (),
			.ff_rx_a_empty ()
		);

		eth_core eth_core_inst (
			.clk          (CLOCK_50),
			.rdclk        (CLOCK_50), // TODO: wire to the actual read-side clock domain once defined
			.rst          (sys_reset),
			.asi_rx       (tse_rx[eth_ch]),
			.asi_rx_ready (tse_rx_ready[eth_ch]),
			.aso_tx       (tse_tx[eth_ch]),
			.aso_tx_ready (tse_tx_ready[eth_ch])
		);
	end
endgenerate

endmodule
